// <auto-generated />
using HealthcareTriage.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HealthcareTriage.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HealthcareTriageDbContext))]
    [Migration("20260426103000_AddCasePatientName")]
    partial class AddCasePatientName
    {
    }
}
